name: Demo-vinayashree

on:
  push:
    branches:
      - main
jobs:
  vinayashree:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Run a one-line script
       run: echo Hello gihub actions
    

   

    
