name: Manually running the file

on:
 workflow_dispatch:
env:
 DAY_OF_WEEK: Monday
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
     Greeting: hello
    steps:
    - name: Environmet declaration
      run: echo "$Greeting $First_name . Today is $DAY_OF_WEEK"
      env:
       First_name: Vinayashree
    
    
  
 
 



    

   

    
