name: Environment variables-vin
on:
 workflow_dispatch:
env:
 DAY_OF_WEEK: Monday
jobs:
 demo:
  runs-on: ubuntu-latest
  env:
    Greeting: hello
  steps:
  - name: Environment declaration
    run: echo "$Greeting $First_name. Today is $DAY_OF_WEEK"
    env:
      First_name: Vinayashree
  
