name: Issue creation

on:
  issues:
    types:
      - opened

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Issue
        uses: actions/checkout@v4

      - name: Test
        run: |
          echo "This is for issue creation"
